# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(default='None', upload_to='images/', verbose_name='photo'),
        ),
    ]
